jwt.expiry=86400
jwt.secret=todo
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
logging.level.org.springframework.security=DEBUG
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.instances.todo.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.todo.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.todo.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.todo.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.todo.register-health-indicator=true
resilience4j.circuitbreaker.instances.todo.sliding-window-size=10
resilience4j.circuitbreaker.instances.todo.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.todo.wait-duration-in-open-state=5s
server.host=localhost
server.port=9000
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.path=/
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=true
spring.application.name=todo
spring.datasource.password=todo
spring.datasource.url=jdbc:mariadb://localhost:3306/todo
spring.datasource.username=todo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
